trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    